### ISSUE TITLE
Oracle Migrations

### ISSUE THREAD

**Issue by whmemon** [amnah/yii2-user#121]
I am unable to run migration script on Oracle 11g.

**Comment by amnah** [comment]
Could you post the error please?

**Comment by whmemon** [comment]
I am using yii2-oci8pdo extension for oracle and getting following error with yii2-user migrations.

in D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO.php:93

Stack trace:
#0 D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO_Connection.php(39):
yii\db\Connection->createPdoInstance()
#1 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(529): sfedosimov\oci8
pdo\Oci8PDO_Connection->createPdoInstance()
#2 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(836): yii\db\Connecti
on->open()
#3 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(823): yii\db\Connecti
on->getMasterPdo()
#4 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Schema.php(477): yii\db\Connection->
getSlavePdo()
#5 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Connection.php(732): yii\db\Schema->
quoteValue()
#6 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Command.php(172): yii\db\Connection-
>quoteValue()
#7 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Command.php(806): yii\db\Command->ge
tRawSql()
#8 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Command.php(359): yii\db\Command->qu
eryInternal()
#9 D:\wamp\www\basic\vendor\yiisoft\yii2\db\oci\Schema.php(148): yii\db\Command-
>queryAll()
#10 D:\wamp\www\basic\vendor\yiisoft\yii2\db\oci\Schema.php(87): yii\db\oci\Sche
ma->findColumns()
#11 D:\wamp\www\basic\vendor\yiisoft\yii2\db\Schema.php(146): yii\db\oci\Schema-
>loadTableSchema()
#12 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\MigrateController.
php(121): yii\db\Schema->getTableSchema()
#13 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateControl
ler.php(610): yii\console\controllers\MigrateController->getMigrationHistory()
#14 D:\wamp\www\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateControl
ler.php(102): yii\console\controllers\BaseMigrateController->getNewMigrations()
#15 D:\wamp\www\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): yii\console
\controllers\BaseMigrateController->actionUp()
#16 D:\wamp\www\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user
_func_array:{D:\wamp\www\basic\vendor\yiisoft\yii2\base\InlineAction.php:55}()
#17 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Inl
ineAction->runWithParams()
#18 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\C
ontroller->runAction()
#19 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Cont
roller->runAction()
#20 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Application.php(167): yii\base
\Module->runAction()
#21 D:\wamp\www\basic\vendor\yiisoft\yii2\console\Application.php(143): yii\cons
ole\Application->runAction()
#22 D:\wamp\www\basic\vendor\yiisoft\yii2\base\Application.php(375): yii\console
\Application->handleRequest()
#23 D:\wamp\www\basic\yii(19): yii\base\Application->run()
#24 {main}

D:\wamp\www\basic>

**Comment by amnah** [comment]
Uhhhh what's the actual error message? I see only the stack trace

Well, looking at the first line `in D:\wamp\www\basic\vendor\sfedosimov\yii2-oci8pdo\Oci8PDO.php:93`

It looks like it's failing to connect to your db. My guess is that your credentials are wrong or your setup is misconfigured.

https://github.com/sfedosimov/yii2-oci8pdo/blob/master/Oci8PDO.php#L93

**Comment by whmemon** [comment]
But my configuration is correct and i am able to generate CRUD with yii2-oci8pdo extension. please see attached image for reference

![untitled](https://cloud.githubusercontent.com/assets/12655625/11996643/38009652-aa89-11e5-960a-bde7438c1754.jpg)

**Comment by amnah** [comment]
You still haven't given me any information. What's the error message? Have you tried walking through the code and seeing what's happening? 

I really can't do much more than make random guesses at this point with how little info I have ...
