### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by EugenyHo** [amnah/yii2-user#86]
lalala$ php yii migrate --migrationPath=@vendor/amnah/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.3)

Total 2 new migrations to be applied:
	m140524_153638_init_user
	m140524_153642_init_user_auth

Apply the above migrations? (yes|no) [no]:yes
*** applying m140524_153638_init_user
    > create table role ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'role' already exists
The SQL being executed was: CREATE TABLE `role` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` varchar(255) not null,
	`create_time` timestamp null default null,
	`update_time` timestamp null default null,
	`can_admin` smallint(6) not null default 0
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB (/var/www/html/mymk-notes/vendor/yiisoft/yii2/db/Schema.php:534)
#0 /var/www/html/mymk-notes/vendor/yiisoft/yii2/db/Command.php(776): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `r...')
#1 /var/www/html/mymk-notes/vendor/yiisoft/yii2/db/Migration.php(248): yii\db\Command->execute()
#2 /var/www/html/mymk-notes/vendor/amnah/yii2-user/migrations/m140524_153638_init_user.php(25): yii\db\Migration->createTable('role', Array, 'CHARACTER SET u...')
#3 /var/www/html/mymk-notes/vendor/yiisoft/yii2/db/Migration.php(81): m140524_153638_init_user->safeUp()
#4 /var/www/html/mymk-notes/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): yii\db\Migration->up()
#5 /var/www/html/mymk-notes/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m140524_153638_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /var/www/html/mymk-notes/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /var/www/html/mymk-notes/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/mymk-notes/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#10 /var/www/html/mymk-notes/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#11 /var/www/html/mymk-notes/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('migrate', Array)
#12 /var/www/html/mymk-notes/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('migrate', Array)
#13 /var/www/html/mymk-notes/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/html/mymk-notes/yii(31): yii\base\Application->run()
#15 {main}
*** failed to apply m140524_153638_init_user (time: 0.016s)

Migration failed. The rest of the migrations are canceled.

**Comment by EugenyHo** [comment]
after delete all tabled in db, migration success!
